### ISSUE TITLE
Webview: center and css logout button

### ISSUE THREAD

**Issue by andrewjaykeller** [neurosity/plugin-vscode-notion#5]
The logout button looks quite horrible and I cannot figure out how to center it.

![image](https://user-images.githubusercontent.com/11437469/71635020-bcebc400-2bee-11ea-8c8a-6a6f4947cc58.png)

**Comment by alexcastillo** [comment]
We can use flexbox for this.

1) Wrap the button in a div container with `class="user-nav"`
2) Add the following css code:

```css
.user-nav {
  display: flex;
  justify-content: center;
}
```
